[package]
name = "taurpc"
authors = ["MatsDK"]
version = "0.3.0-alpha.2"
edition = "2021"
description = "A type-safe IPC layer for tauri commands"
documentation = "https://docs.rs/taurpc"
homepage = "https://github.com/MatsDK/TauRPC"
repository = "https://github.com/MatsDK/TauRPC"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["tauri"]
rust = "1.71"

[workspace]
members = [
  "taurpc-macros",
]

[dependencies]
taurpc-macros = { path = "./taurpc-macros", version = "=0.3.0-alpha.2" }

specta = { version = "1.0.5", features = ["export"] }
tauri = "=2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1", features = ["full"] }
